### ISSUE TITLE
Not sure how to reach you

### ISSUE THREAD

**Issue by chetsmith** [joseftw/jos.tips-and-trix#1]
Hello, Josef 

I'm not sure how to best reach you. I sent you a tweet, but since I don't use twitter, I'm not sure it will reach you. I'd like to see if you are available to discuss consulting work for a WOPI project my company is working on. Please let me know. I would like to discuss. 

Thanks,
Chet Smith

**Comment by joseftw** [comment]
Hello! You can email me at josef @jeho.se
